package com.matete.agentmanage.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("agent", "ID", Agent.class);
		arp.addMapping("property", "ID", Property.class);
		arp.addMapping("record_login", "ID", RecordLogin.class);
		arp.addMapping("record_recharge", "ID", RecordRecharge.class);
	}
}

