package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseAccountuserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accountuserinfo extends BaseAccountuserinfo<Accountuserinfo> {
	public static final Accountuserinfo dao = new Accountuserinfo().dao();
}
