package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseProxyUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProxyUser extends BaseProxyUser<ProxyUser> {
	public static final ProxyUser dao = new ProxyUser().dao();
}
