package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseRechargerecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rechargerecord extends BaseRechargerecord<Rechargerecord> {
	public static final Rechargerecord dao = new Rechargerecord().dao();
}
