package com.matete.agentmanage.model;

import com.matete.agentmanage.model.base.BaseRoomcard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roomcard extends BaseRoomcard<Roomcard> {
	public static final Roomcard dao = new Roomcard().dao();
}
