package com.matete.agentmanage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRechargerecord<M extends BaseRechargerecord<M>> extends Model<M> implements IBean {

	public M setGameID(java.lang.Integer GameID) {
		set("GameID", GameID);
		return (M)this;
	}

	public java.lang.Integer getGameID() {
		return get("GameID");
	}

	public M setScoreCount(java.lang.Integer ScoreCount) {
		set("ScoreCount", ScoreCount);
		return (M)this;
	}

	public java.lang.Integer getScoreCount() {
		return get("ScoreCount");
	}

	public M setRechargeTime(java.lang.String RechargeTime) {
		set("RechargeTime", RechargeTime);
		return (M)this;
	}

	public java.lang.String getRechargeTime() {
		return get("RechargeTime");
	}

	public M setAgentGameID(java.lang.Integer AgentGameID) {
		set("AgentGameID", AgentGameID);
		return (M)this;
	}

	public java.lang.Integer getAgentGameID() {
		return get("AgentGameID");
	}

	public M setOddNumbers(java.lang.String OddNumbers) {
		set("OddNumbers", OddNumbers);
		return (M)this;
	}

	public java.lang.String getOddNumbers() {
		return get("OddNumbers");
	}

	public M setMoney(java.lang.Integer money) {
		set("money", money);
		return (M)this;
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setInvitecode(java.lang.Integer invitecode) {
		set("invitecode", invitecode);
		return (M)this;
	}

	public java.lang.Integer getInvitecode() {
		return get("invitecode");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
